import { db } from "./firebaseConfig";
import { doc, updateDoc, increment } from "firebase/firestore";

export const adminGenerateTokens = async (userId, amount) => {
  const userRef = doc(db, "users", userId);
  await updateDoc(userRef, {
    tokens: increment(amount)
  });
  alert("Unlimited Tokens Generated by Admin!");
};
